[package]
name = "bevy-2d-game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.16.0"
bevy-inspector-egui = "0.31.0"
noise-functions = "0.8.1"
strum = { version = "0.27.1", features = ["derive"] }
bytemuck = { version = "1.22", features = ["extern_crate_alloc"] }
